version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: mysql-5.7
    volumes:
      - "db-data:/var/lib/mysql"
      - "./init/:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "hello"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 9090:8080

volumes:
  db-data:
